### ISSUE TITLE
Command format

### ISSUE THREAD

**Issue by tmichel** [Kresshy/node-ircbot#4]
This is basically the user interface of the bot, so I think it crucial to agree upon a format that everybody supports.

Personally I would like to minimize the noise in the public channel. I would create 2 classes of commands:

1. commands for public interest such as `here` (see #3)
2. commands that only relevant for a single user (eg `history`

We also have to agree upon a command prefix which is currently `@` but that might be confusing since it used as addressing somebody everywhere else. Maybe the exclamation mark (!) would be more intention revealing.

cc @Kresshy, @vbalazs, @zolij, @aldaris

**Comment by Kresshy** [comment]
First of all let's decide what should be the command prefix. I think these symbols are suitable for the job:

@, $, !, #

Any other idea or which would you choose? :construction:

**Comment by aldaris** [comment]
* # usually refers to numbers, or to IRC channels
* @ usually is used for addressing people

Both $ and ! sound feasible to me, but I would vote for ! if possible. (In bash you can run !ps to execute the last ps command in bash history, so would feel closer to command line :))

**Comment by Kresshy** [comment]
Okay, then I'm going to change the prefix to "!".

Next we should collect a feature / command set and discuss the public and private interfaces.

Please add what features would you like to have in the application and what interface it should have.

There will be a web application so you can consider having this also when suggesting features.

**Comment by tmichel** [comment]
:+1: for !

My primary use case would be logging and reading logs. The web UI for the log viewer I think one of the most important parts of the bot (if not _the_ most important part). Reading and searching through logs but I think this one needs its own issue.

I think we can close this issue if nobody has anything against `!` as the command prefix.

**Comment by zolij** [comment]
i'm vote for ! :)
